name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
    - boto3
    - pandas
    - pytest
    - mlflow==1.14.1
    - opencv-python
    - matplotlib
    - markupsafe
