main:
  components_repository: "https://github.com/TuanAnhNguyen14111998/nd0821-c2-build-model-workflow-starter.git#components"
  project_name: tracking_experiments
  experiment_name: development
  steps: all
etl:
  bucket_name: "mlflow"
  folder_path: "../../data/images/"
  path_info: "../../data/information/dataset/train.csv,../../data/information/dataset/test.csv"
  artifact_name: "train.csv,test.csv"
  artifact_type: "csv"
  storage_id: "683b3bf7c5d8410db67b0d9dc04f35b9"
data_check:
  train_pos_num: 1000
  train_neg_num: 1000
  test_pos_num: 250
  test_neg_num: 250
modeling:
  random_seed: 42
  stratify_by: ""
  image_size: 256
  data_path: "../../data/images/"
  output_artifact: "../../data/outputs/"
  densenet121:
    model_name: "convnext_TA"
    classes: "Classes"
    node_num: 1024
    min_lr: 5e-2
    max_lr: 2e-1
    epoch_num: 1
    batch_size: 5
    n_workers: 8
