name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
      - mlflow==1.14.1
      - boto3
      - torch
      - torchvision  -f https://download.pytorch.org/whl/torch_stable.html
      - scikit-learn
      - matplotlib
      - pillow
      - opencv-python
      - pandas
      - protobuf==3.20
      - psycopg2
      - torch_lr_finder
      - albumentations
      - IPython
      - fastprogress
      - timm
