name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
      - mlflow==1.14.1
      - psycopg2
      - boto3
      - git+https://github.com/TuanAnhNguyen14111998/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
